// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlxeTEuev_ObR2Y2fy3NRzIleRd9_FTfE',
    appId: '1:292443165218:web:e076cf6edad1f3e3e6f07b',
    messagingSenderId: '292443165218',
    projectId: 'wisenote',
    authDomain: 'wisenote.firebaseapp.com',
    storageBucket: 'wisenote.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRRmXc5FQUGvC5Ck5b6F0CB5NxZDXIbKE',
    appId: '1:292443165218:android:3964130250edada9e6f07b',
    messagingSenderId: '292443165218',
    projectId: 'wisenote',
    storageBucket: 'wisenote.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWTtrCLvaNvA_OjGF449Cx-Ce565ENxSo',
    appId: '1:292443165218:ios:dcdd81865a063ac3e6f07b',
    messagingSenderId: '292443165218',
    projectId: 'wisenote',
    storageBucket: 'wisenote.appspot.com',
    iosBundleId: 'com.wisenote.ua.wisenote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWTtrCLvaNvA_OjGF449Cx-Ce565ENxSo',
    appId: '1:292443165218:ios:2034175cba7235e1e6f07b',
    messagingSenderId: '292443165218',
    projectId: 'wisenote',
    storageBucket: 'wisenote.appspot.com',
    iosBundleId: 'com.wisenote.ua.wisenote.RunnerTests',
  );
}
